name: Automate-pushing

on:
  push:

jobs:
  My-build:
      runs-on: ubuntu-latest
      steps:
      - name: Setup SSH Agent
        uses: yakuhzi/setup-ssh-agent@v1.5.4
        with:
          public: ${{ secrets.KEY }}       
      - uses: actions/checkout@v1
      - name: Run a one-line script
        run: |
          echo push to GitHub!
          git remote add bitbuck git@bitbucket.org:mikevoice/my_repo.git
          git remote add gitlab git@gitlab.com:mikevoice/my_repo.git          
          git remote -v
          echo push to Bitbucket!
          git push bitbuck --all
          echo push to GitLab!
          git push gitlab --all
